### ISSUE TITLE
EADDR in use?

### ISSUE THREAD

**Issue by scheung38** [hunterloftis/throng#25]
How to avoid EADDR in use?

app.js:

throng((id) => {

  console.log(`Started worker ${id}`);

});

**Comment by cata-libuy** [comment]
Hello
I'm facing the sam issue when trying to run in local.

Even if I set the workers to 2 or 1, it just keeps creating processes and throwing the error of EADDR in use.

**This is the code:**

`// Libs
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const busboy = require('connect-busboy')
const throng = require('throng')

// Api
const api = require('./api')

app.use(cors())
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())
app.use(busboy({ immediate: true })) // Recibe archivos

// Habilita procesos paralelos
const WORKERS = process.env.WEB_CONCURRENCY || 1
const processStart = (processId) => {
  console.log('starting process', processId)
  console.log('workers: ', WORKERS)
}
throng({
  workers: WORKERS,
  lifetime: Infinity
}, processStart)


app.set('port', (process.env.PORT || 5000))

// HelloWorld
app.get('/', api.helloWorld)

// UploadCsv
app.post('/api/uploads/campaign/:campaign/dataType/:dataType/', api.uploadCsv)

// Valida y envía un correo al usuario del cupon
app.post('/api/mail/campaign/:campaign', api.sendCampaignMail)

// ByPass simple con llamada a productos de sico (workaround problema certificado)
app.post('/api/v3/:campaign/product/search/', api.getSicoProducts)

app.listen(app.get('port'), function() {
  console.log('hello');
  console.log('Node app is running on port', app.get('port'));
})`

**This is the command I use for running it:**

`ENV=development WEB_CONCURRENCY=2 node server.js`

**This is the error (keeps repeating):**

`hello
Node app is running on port 5000

starting process 1
workers:  2
starting process 2
workers:  2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at cb (net.js:1317:16)
    at rr (cluster.js:626:14)
    at Worker.<anonymous> (cluster.js:595:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at cb (net.js:1317:16)
    at rr (cluster.js:626:14)
    at Worker.<anonymous> (cluster.js:595:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
starting process 4
workers:  2
starting process 3
workers:  2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at cb (net.js:1317:16)
    at rr (cluster.js:626:14)
    at Worker.<anonymous> (cluster.js:595:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:5000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at cb (net.js:1317:16)
    at rr (cluster.js:626:14)
    at Worker.<anonymous> (cluster.js:595:9)
    at process.<anonymous> (cluster.js:766:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
starting process 6
workers:  2
starting process 5
workers:  2
events.js:160`

and goes on until I stop the process with `ctrl+c`...

**Comment by gonenduk** [comment]
It seems like you are trying to make the app listen on the port both from the workers and from the master.
On the master it is best not to load any module and not to open any ports.
The app.listen should only happen in the workers. They tell the master what port to listen to. If the master already listetning to that port - an error will happen.
I'm using throng for 3 days already with my base server project. You can check what I did there:
[gonenduk/basejs](https://www.github.com/gonenduk/basejs)

**Comment by darkcody** [comment]
I'm having the same issue. The worker I'm registering doesn't open any ports, but I get the port conflict when I run the following:

```js
// index.js
const express = require('express');
const app = express();
const port = process.env.PORT;
require('./worker');
app.listen(port, () => console.log(`Listening on port ${port}`));


// worker.js
const throng = require('throng');

function worker() {
  setInterval(() => {
    console.log('werk');
  }, 1000);
}

throng({
  workers: 1,
  start: worker
});

```

**Comment by hunterloftis** [comment]
Anything top-level will be run in all processes (both master and forked). So @darkcody that `app.listen()` is being run twice. You can put it in a `master` process or a `worker` process but you can't listen to the same port in both.
